<a href="https://colab.research.google.com/github/ShilpaVasista/Exploratory-Data-Analytics/blob/main/Module_2_Practice_Session_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Outlier Detection and Filtering

 Loading the Dataset

In [5]:
# Import required libraries
import pandas as pd

# Load the dataset from GitHub
df = pd.read_csv('sales.csv')

# Display the first 10 rows of the dataset
df.head(10)

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete
0,123456779,Kulas Inc,99985,s9-supercomputer,Aruba,1981,5148,545,False
1,123456784,GitHub,99986,s4-supercomputer,Brazil,2001,3262,383,False
2,123456782,Kulas Inc,99990,s10-supercomputer,Montserrat,1973,9119,407,True
3,123456783,My SQ Man,99999,s1-supercomputer,El Salvador,2015,3097,615,False
4,123456787,ABC Dogma,99996,s6-supercomputer,Poland,1970,3356,91,True
5,123456778,Super Sexy Dingo,99996,s9-supercomputer,Costa Rica,2004,2474,136,True
6,123456783,ABC Dogma,99981,s11-supercomputer,Spain,2006,4081,195,False
7,123456785,ABC Dogma,99998,s9-supercomputer,Belarus,2015,6576,603,False
8,123456778,Loolo INC,99997,s8-supercomputer,Mauritius,1999,2460,36,False
9,123456775,Kulas Inc,99997,s7-supercomputer,French Guiana,2004,1831,664,True

Adding a New Column: TotalPrice
Code Block: Calculate the TotalPrice for each transaction.

In [7]:
# Add a new column 'TotalPrice'
df['TotalPrice'] = df['UnitPrice'] * df['Quantity']

# Display the dataset with the new column
df.head()

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete,TotalPrice
0,123456779,Kulas Inc,99985,s9-supercomputer,Aruba,1981,5148,545,False,2805660
1,123456784,GitHub,99986,s4-supercomputer,Brazil,2001,3262,383,False,1249346
2,123456782,Kulas Inc,99990,s10-supercomputer,Montserrat,1973,9119,407,True,3711433
3,123456783,My SQ Man,99999,s1-supercomputer,El Salvador,2015,3097,615,False,1904655
4,123456787,ABC Dogma,99996,s6-supercomputer,Poland,1970,3356,91,True,305396

Detecting Outliers

Code Block: Identify transactions where TotalPrice > 3,000,000.

In [8]:
# Detect outliers where TotalPrice > 3,000,000
outliers = df[df['TotalPrice'] > 3000000]

# Display the outliers
outliers

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete,TotalPrice
2,123456782,Kulas Inc,99990,s10-supercomputer,Montserrat,1973,9119,407,True,3711433
7,123456785,ABC Dogma,99998,s9-supercomputer,Belarus,2015,6576,603,False,3965328
13,123456788,Will LLC,99995,s2-supercomputer,Niger,2008,8700,547,False,4758900
15,123456775,SAS Web Tec,99993,s5-supercomputer,Kazakhstan,1998,8707,596,True,5189372
17,123456785,GitHub,99999,s2-supercomputer,Switzerland,1978,6185,645,False,3989325
...,...,...,...,...,...,...,...,...,...,...
9977,123456788,Kirlosker Service Center,99989,s7-supercomputer,Romania,2010,5104,681,True,3475824
9984,123456789,Kulas Inc,99996,s2-supercomputer,Samoa,2010,7791,674,True,5251134
9987,123456788,GitHub,99989,s9-supercomputer,Cote d'Ivoire,1986,8805,644,True,5670420
9991,123456772,Will LLC,99982,s9-supercomputer,Kiribati,1988,8447,679,False,5735513
9996,123456775,Will LLC,99985,s3-supercomputer,Vietnam,2002,9995,302,True,3018490

Displaying Rows with Extreme Outliers

Objective: Display rows where TotalPrice > 6,741,112.

In [11]:
# Detect extreme outliers where TotalPrice > 6,741,112
extreme_outliers = df[df['TotalPrice'] > 6741112]

# Display extreme outliers
extreme_outliers

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete,TotalPrice
818,123456781,Gen Power,99991,s1-supercomputer,Burkina Faso,1985,9693,696,False,6746328
1402,123456778,Will LLC,99985,s11-supercomputer,Austria,1990,9844,695,True,6841580
2242,123456770,Name IT,99997,s9-supercomputer,Myanmar,1979,9804,692,False,6784368
2876,123456772,Gen Power,99992,s10-supercomputer,Mali,2007,9935,679,False,6745865
3210,123456782,Loolo INC,99991,s8-supercomputer,Kuwait,2006,9886,692,False,6841112
3629,123456779,My SQ Man,99980,s3-supercomputer,Hong Kong,1994,9694,700,False,6785800
7674,123456781,Loolo INC,99989,s6-supercomputer,Sri Lanka,1994,9882,691,False,6828462
8645,123456789,Gen Power,99996,s11-supercomputer,Suriname,2005,9742,699,False,6809658
8684,123456785,Gen Power,99989,s2-supercomputer,Kenya,2013,9805,694,False,6804670

Practice Exercise

You are tasked with analyzing a dataset from the healthcare domain. The dataset contains information about hospital patients, including their demographic details, health metrics, and medical expenses. One of the critical goals of this analysis is to detect patients whose total medical expenses are unusually high, indicating potential outliers. This will help hospitals better understand high-cost cases and develop more cost-effective treatment plans.

Dataset:
insurance.csv

Dataset Columns:

- age: Age of the policyholder.
- sex: Gender of the policyholder (male/female).
- bmi: Body mass index of the policyholder (a measure of body fat based on height and weight).
- children: Number of children/dependents covered by the policy.
- smoker: Indicates if the policyholder is a smoker (yes/no).
- region: The region of the policyholder (northeast, northwest, southeast, southwest).
- charges: Total medical charges billed to the policyholder.

Tasks:
1. Outlier Detection Based on Charges:
Detect policyholders with unusually high insurance charges (charges > $30,000). Display details of these policyholders, including age, bmi, smoker, and charges.

2. Statistical Summary of Charges:
Compute the mean, median, and standard deviation of the charges column.
Compare the summary statistics of smokers vs. non-smokers.
3. Extreme Outlier Analysis:
Identify extreme outliers where charges > $50,000.
List details of these policyholders and analyze the relationship between bmi, age, and smoker status.
4. BMI and Smoking Analysis:
Filter the dataset for smokers with a bmi > 30 (considered obese).
Calculate the average charges for this group compared to non-obese smokers (bmi <= 30).
5. Filtering by Region:
Create a new dataset excluding policyholders from the southeast region, as this region has a different risk profile.

Hints and Tips:

1. Outlier Detection:

  Use thresholds (30,000 and 50,000) to filter rows where charges exceed these values.

2. Statistical Summary:

  Use statistical functions to calculate the mean, median, and standard deviation. Group by smoker to compare values.

3. Relationships:

  Analyze the relationship between bmi and charges using grouped statistics or filtering techniques.
4. Region Filtering:

  Exclude rows where region = southeast using conditional filtering.
5. Data Visualization (Optional):

  - Create box plots to visualize the distribution of charges for smokers vs. non-smokers.
  - Use scatter plots to explore the relationship between bmi and charges.